version: '3.7'
services:
  tester:
    build:
      context: .
      dockerfile: Dockerfile.test
    command: >
      sh -c "go mod download &&
             ./bin/golangci-lint run -v &&
             go test ./..."
